### ISSUE TITLE
develop MPMS_plot_ac notebook and associated functions

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/RockmagPy-notebooks#12]
Another notebook is needed that can be called MPMS_plot_ac in order to plot data (and do associated calculations) for susceptibility as a function of temperature, applied field and frequency. 

`ipmag.chi_magic()` is a starting place for this:
https://pmagpy.github.io/PmagPy-docs/documentation_notebooks/PmagPy_plots_analysis.html#chi-magic

That section of the PmagPy_calculations.ipynb also has some code that reads in from the measurements table using pandas. At present, that code is working on a version of the measurements file in a local directory. It would be nice to update to read in from MagIC (but there is currently an error in the first attempt to apply the code to that unpacked measurements file).

A branch is started for developing this notebook:
https://github.com/PmagPy/RockmagPy-notebooks/tree/MPMS_plot_ac

**Comment by Swanson-Hysell** [comment]
Here the key is to develop and test on IRM MagIC export data. It would be nice to pull in data from the from MagIC using the `share_key` parameter in `ipmag.download_magic_from_id(magic_id, directory='.', share_key='')`

**Comment by duserzym** [comment]
closing task with commit 8801df6
