### ISSUE TITLE
merge multiple entities in IRM exposure specimens table

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/RockmagPy-notebooks#14]
At present, the IRM MagIC export produces a separate row for every experiment conducted on a specimen. It makes sense to merge these together so that there is one entry per 

There could be the difficulty that it is possible that there could be conflicts with such a merge. Such as scenarios where a loop is measured both on a VSM and a MPMS with different associated parameters. However, I think that adhering to the data model without repeating specimen entries is preferable. Otherwise, the Bcr would be a different entry than the Bc, Mr, Ms for example as it is estimated in a different experiment.

**Comment by peat22** [comment]
How would we handle hysteresis loops at different temperatures on the same
specimen with only one entry per specimen?

**Comment by Swanson-Hysell** [comment]
You're right. They really isn't a way around having to have multiple entries per specimen for experiments such as loops at different temperatures where there are going to be different summary parameters that one would want to record at the specimen level. And if there are situations where we need to output a different row for each experiment, I guess it then makes sense to always output a different row for each experiment. Its ends up being a bit awkward for a few different reasons with the wanting to have Bcr, Br, Mr, and Ms all together as just one. 

This ends up being a similar situation to the locations table which is the locations+poles table where the specimens table ends up being the specimens+experiments table given that specimens will be reported.

For dealing with writing out summary parameters, I guess we need to look to the row with a given method code so that the summary parameter is written out for the right experiment. There is an advantage here where there are instances where you would want to estimate something like the Verwey transition for both the FC and ZFC LTSIRM curve.
