### ISSUE TITLE
missing holder measurement in the IRMDB export for high T susceptibility 

### ISSUE THREAD

**Issue by duserzym** [PmagPy/RockmagPy-notebooks#27]
The IRMDB export for high T susceptibility (perhaps in both the MagIC format and excel format) is missing the holder measurements. We need to subtract the holder to show the correct susceptibility values. This example below shows data from SSRM2022C group project plotted from the MagIC export:
![image](https://github.com/PmagPy/RockmagPy-notebooks/assets/39976081/40163e92-f7af-4217-b18a-5cb936ae8f69)

whereas the correct plot should look like this (processed using the excel export from 2 years ago):
![image](https://github.com/PmagPy/RockmagPy-notebooks/assets/39976081/7187ddf1-4782-4bb0-9df2-a3a9f2ed9e24)

The Y-axis values in the first figure are all negative... I think we need help from @peat22 again! Thank you!!

**Comment by Swanson-Hysell** [comment]
Thanks @peat22!
