### ISSUE TITLE
make a .md file that explains getting going on JupyterHub

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/RockmagPy-notebooks#29]
This can be a markdown file that explains how to:
- upload the `rockmag_set_up.ipynb` notebook to JupyterHub
- run that notebook on JupyterHub to pull in the latest pmagpy and latest rockmagpy repo
- include a warning that running this notebook again will overwrite files in the rockmagpy folder (show how to rename the folder)

**Comment by duserzym** [comment]
I just edited the rockmagpy_set_up.ipynb. [7d6f12c](https://github.com/PmagPy/RockmagPy-notebooks/commit/7d6f12ce9bd6f53ef0f0ea4ef638a0bcaec5391c)

I thought the markdown cell in that notebook was good to work with and that there is already a toc item linked to the notebook for getting going. Maybe we just use that markdown in the notebook? It would be easy to pull those md cells into an individual file though.

**Comment by Swanson-Hysell** [comment]
Looks good!
