### ISSUE TITLE
make another MPMS notebook that enables the goethite component to be fit and removed

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/RockmagPy-notebooks#9]
This would be similar to the Verwey fit function, but be done on the Ms-T curve. Could integrate the ability to exclude certain temperature windows as in the Verwey temperature fit function.

**Comment by maxwellbrown** [comment]
The fit would be on the warming curve of the RT-SIRM cycle above Tv.

**Comment by Swanson-Hysell** [comment]
@maxwellbrown Can you send along or commit to the data folder an example dataset that has been exported from the IRM database in MagIC format that is a particularly good example of applying this method? I can use that dataset both to develop the functions and we can have it in the notebook as the example.

**Comment by Swanson-Hysell** [comment]
I have started a notebook in this regard in this branch:
https://github.com/PmagPy/RockmagPy-notebooks/tree/MPMS-goethite-notebook

start of notebook can be seen rendered here:
https://github.com/PmagPy/RockmagPy-notebooks/blob/MPMS-goethite-notebook/MPMS_goethite_fit.ipynb

@maxwellbrown, can you point me to a paper in the literature that applies such a numerical approach to subtract the goethite contribution from RTSIRM curves. There are plenty examples of doing it experimentally through 400 K heating in the context of the goethite test, but I would like to refer to examples of the numerical approach you are describing implementing here. There is a linear fit approach taken for a residual increasing while cooling slope in Fig. 6 of [Bilardello, 2009](https://drive.google.com/file/d/1f425KX5fsiNeswUnGQbpYov1hTfQA4ib/view?usp=sharing).
